config/routes.rb
Rails.application.routes.draw do
  root 'employees#index'

  resources :employees
  resources :jobs
  resources :orgs
  resources :employee_statuses

  devise_for :users
  resources :users, only: [:index]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/employee.rb
class Employee < ApplicationRecord
  belongs_to :job
  belongs_to :org
  belongs_to :employee_status
  has_many :subordinates, class_name: 'Employee', foreign_key: 'manager_id'
  belongs_to :manager, class_name: 'Employee', optional: true

  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :job_id, presence: true
  validates :org_id, presence: true
  validates :code, presence: true, uniqueness: true

  scope :active, -> { where(employee_status_id: [1, 2]) }

  def self.search(search)
    if search
      where('lower(first_name) LIKE :search OR lower(last_name) LIKE :search OR code = :code',
            search: "#{search.downcase}%", code: search.to_i)
    else
      all
    end
  end

  def full_name
    "#{first_name} #{last_name}".titleize
  end
end

app/models/employee_status.rb
class EmployeeStatus < ApplicationRecord
  has_many :employees

  validates :code, presence: true
  validates :name, presence: true
end

app/models/job.rb
class Job < ApplicationRecord
  has_many :employees
  validates :code, presence: true
  validates :name, presence: true
end

app/models/org.rb
class Org < ApplicationRecord
  has_many :employees
  validates :code, presence: true
  validates :name, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  
  def active_for_authentication?
    super && approved?
  end

  def inactive_message 
    approved? ? super : :not_approved
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name])
  end
end

app/controllers/employee_statuses_controller.rb
class EmployeeStatusesController < ApplicationController
  before_action :authenticate_user!

  def index
    @employee_statuses = EmployeeStatus.order("#{params[:column]} #{params[:direction]}").paginate(page: params[:page],
                                                                                                   per_page: 10)
  end

  def show
    @employee_status = EmployeeStatus.find(params[:id])
  end

  def new
    @employee_status = EmployeeStatus.new
  end

  def create
    @employee_status = EmployeeStatus.new(employee_status_params)

    if @employee_status.save
      flash[:notice] = "#{@employee_status.name} created!"
      redirect_to employee_statuses_path
    else
      render :new
    end
  end

  def edit
    @employee_status = EmployeeStatus.find(params[:id])
  end

  def update
    @employee_status = EmployeeStatus.find(params[:id])

    if @employee_status.update(employee_status_params)
      redirect_to @employee_status
    else
      render :edit
    end
  end

  def destroy
    @employee_status = EmployeeStatus.find(params[:id])
    @employee_status.destroy
    flash[:notice] = "#{@employee_status.name} deleted!"
    redirect_to employee_statuses_path
  end

  private

  def employee_status_params
    params.require(:employee_status).permit(:code, :name)
  end
end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
  before_action :authenticate_user!

  def index
    @employees = Employee.search(params[:query])
                         .order("#{params[:column]} #{params[:direction]}")
                         .paginate(page: params[:page], per_page: 10)
    @show_all = params[:all]
    if @show_all == 'true'
      @employees
    else
      @employees = @employees.active
      @show_all = false
    end
  end

  def show
    @employee = Employee.find(params[:id])
  end

  def new
    @employee = Employee.new
  end

  def create
    @employee = Employee.new(employee_params)

    if @employee.save
      flash[:notice] = "#{@employee.first_name} #{@employee.last_name} created!"
      redirect_to employees_path
    else
      render :new
    end
  end

  def edit
    @employee = Employee.find(params[:id])
  end

  def update
    @employee = Employee.find(params[:id])

    if @employee.update(employee_params)
      redirect_to employees_path
    else
      render :edit
    end
  end

  def destroy
    @employee = Employee.find(params[:id])
    @employee.destroy
    flash[:notice] = "#{@employee.full_name} deleted!"
    redirect_to employees_path
  end

  private

  def employee_params
    params.require(:employee).permit(:first_name, :last_name, :job_id, :org_id, :manager_id, :employee_status_id,
                                     :code, :query, :all, :column, :direction)
  end
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  before_action :authenticate_user!

  def index
    @jobs = Job.order("#{params[:column]} #{params[:direction]}")
               .paginate(page: params[:page], per_page: 10)
  end

  def show
    @job = Job.find(params[:id])
  end

  def new
    @job = Job.new
  end

  def create
    @job = Job.new(job_params)

    if @job.save
      flash[:notice] = "#{@job.name} created!"
      redirect_to jobs_path
    else
      render :new
    end
  end

  def edit
    @job = Job.find(params[:id])
  end

  def update
    @job = Job.find(params[:id])

    if @job.update(job_params)
      redirect_to @job
    else
      render :edit
    end
  end

  def destroy
    @job = Job.find(params[:id])
    @job.destroy
    flash[:alert] = "#{@job.name} deleted!"
    redirect_to jobs_path
  end

  private

  def job_params
    params.require(:job).permit(:name, :code)
  end
end

app/controllers/orgs_controller.rb
class OrgsController < ApplicationController
  before_action :authenticate_user!

  def index
    @orgs = Org.order("#{params[:column]} #{params[:direction]}")
               .paginate(page: params[:page], per_page: 10)
  end

  def show
    @org = Org.find(params[:id])
  end

  def new
    @org = Org.new
  end

  def create
    @org = Org.new(org_params)

    if @org.save
      flash[:notice] = "#{@org.name} created!"
      redirect_to orgs_path
    else
      render :new
    end
  end

  def edit
    @org = Org.find(params[:id])
  end

  def update
    @org = Org.find(params[:id])

    if @org.update(org_params)
      redirect_to @org
    else
      render :edit
    end
  end

  def destroy
    @org = Org.find(params[:id])
    @org.destroy
    flash[:notice] = "#{@org.name} deleted!"
    redirect_to orgs_path
  end

  private

  def org_params
    params.require(:org).permit(:name, :code)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def index
    @users = User.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def sort_link(column:, label:, table:)
    if column == params[:column]
      # link_to(label, employees_path(column: column, direction: next_direction))
      link_to(label, eval("#{table}_path(column: column, direction: next_direction)"))
    else
      # link_to(label, employees_path(column: column, direction: 'asc'))
      link_to(label, eval("#{table}_path(column: column, direction: 'asc')"))

    end
  end

  def next_direction
    params[:direction] == 'asc' ? 'desc' : 'asc'
  end
end

app/helpers/employee_statuses_helper.rb
module EmployeeStatusesHelper
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/helpers/orgs_helper.rb
module OrgsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/employee_statuses/_form.html.erb
<%= form_with model: employee_status do |form| %>
  <div class="row g-2">
    <div class="col-md-4">
      <%= form.label :code, class: 'form-label' %>
      <%= form.text_field :code, class: 'form-control' %>
      <% employee_status.errors.full_messages_for(:code).each do |message| %>
        <div class=""><%= message %></div>
      <% end %>
    </div>
  </div>

  <div class="row g-2 mb-2">
    <div class="col-md-4">
      <%= form.label :name, class: 'form-label' %>
      <%= form.text_field :name, class: 'form-control' %>
      <% employee_status.errors.full_messages_for(:name).each do |message| %>
        <div class=""><%= message %></div>
      <% end %>
    </div>
  </div>
  <div class="col-auto">
    <%= form.submit 'Create Status', class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/employee_statuses/_table.html.erb
<div class="table">
  <table class="table table-hover">
    <thead class="table-secondary">
      <tr>
        <th scope="col"><%= sort_link column: 'code', label: 'Code', table: 'employee_statuses' %></th>
        <th scope="col"><%= sort_link column: 'name', label: 'Name', table: 'employee_statuses' %></th>
        <th scope="col">Delete</th>
      </tr>
    </thead>
    <tbody>
      <% @employee_statuses.each do |status| %>
      <tr>
        <th scope="row"><%= status.code %></th>
        <td><%= link_to status.name, edit_employee_status_path(status) %></td>
        <td>
          <%= link_to 'Delete', employee_status_path(status),
                  method: :delete,
                  data: { confrim: 'Are you sure?' } %> 
        </td>
      </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/employee_statuses/edit.html.erb
<h1>Edit Employee Status</h1>

<%= render 'form', employee_status: @employee_status %>

app/views/employee_statuses/index.html.erb
<div class="row mb-3">
  <div class="col-md-6">
    <h1>Employees Statuses</h1>
  </div>
  <div class="col-md-6 text-end">
    <%= button_to 'New Status', new_employee_status_path, class: "btn btn-outline-primary", method: :get %>
  </div>
</div>
<%= render 'employee_statuses/table' %>
<%= will_paginate @employee_statuses %>

app/views/employee_statuses/new.html.erb
<h1>New Employee Status</h1>

<%= render 'form', employee_status: @employee_status %>

app/views/employee_statuses/show.html.erb
<h1><%= "#{@employee_status.name} - #{@employee_status.code}" %></h1>

app/views/employees/_form.html.erb
<%= form_with model: @employee do |form| %>
  <div class="row mb-2">
    <div class="col-md-4">
      <%= form.label :code, class: 'form-label' %>
      <%= form.text_field :code, value: "#{ Employee.maximum('code') + 1 }", class: 'form-control' %>
      <% @employee.errors.full_messages_for(:code).each do |message| %>
        <div class=""><%= message %></div>
      <% end %>
    </div>
  </div>

  <div class="row mb-2">
    <div class="col-md-4">
      <%= form.label :first_name, class: 'form-label' %>
      <%= form.text_field :first_name, class: 'form-control' %>
      <% @employee.errors.full_messages_for(:first_name).each do |message| %>
        <div class=""><%= message %></div>
      <% end %>
    </div>
  </div>
  <div class="row mb-2">
    <div class="col-md-4">
      <%= form.label :last_name, class: 'form-label' %>
      <%= form.text_field :last_name, class: 'form-control' %>
      <% @employee.errors.full_messages_for(:last_name).each do |message| %>
        <div class=""><%= message %></div>
      <% end %>
    </div>
  </div>

  <div class="row mb-2">
    <div class="col-md-4">
      <%= form.label :job_id, class: 'form-label' %>
      <%= form.collection_select :job_id, Job.order(:name), :id, :name, {}, {class: 'form-select'} %>
      <% @employee.errors.full_messages_for(:job_id).each do |message| %>
        <div class=""><%= message %></div>
      <% end %>
    </div>
  </div>

  <div class="row mb-2">
    <div class="col-md-4">
      <%= form.label :org_id, class: 'form-label' %>
      <%= form.collection_select :org_id, Org.order(:name), :id, :name, {}, { class: 'form-select'} %>
      <% @employee.errors.full_messages_for(:org_id).each do |message| %>
        <div class=""><%= message %></div>
      <% end %>
    </div>
  </div>


  <div class="row mb-2">
    <div class="col-md-4">
      <%= form.label :manager_id, class: 'form-label' %>
      <%= form.collection_select :manager_id, Employee.order(:first_name), :id, :full_name, {}, { class: 'form-select' } %>
      <% @employee.errors.full_messages_for(:manager_id).each do |message| %>
        <div class=""><%= message %></div>
      <% end %>
    </div>
  </div>

  <div class="row mb-2">
    <div class="col-md-4">
      <%= form.label :employee_status_id, class: 'form-label' %>
      <%= form.collection_select :employee_status_id, EmployeeStatus.order(:name), :id, :name, {}, { class: 'form-select' } %>
      <% @employee.errors.full_messages_for(:employee_status_id).each do |message| %>
        <div class=""><%= message %></div>
      <% end %>
    </div>
  </div>

  <div class="col-auto">
    <%= form.submit class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/employees/_search_form.html.erb
<%= form_with url: employees_path, method: :get do |f| %>
  <div class="row g-2 mb-4">
    <div class="col-md-3">
    <%= f.text_field :query, value: params[:query], placeholder: 'Search...', class: 'form-control' %>
    </div>
    <div class="col-md-1">
      <%= f.hidden_field :all, value: params[:all] %>
      <%= f.submit 'Search', name: nil, class: 'btn btn-primary' %>
    </div>
    <div class="col-md-3">
      <% if @show_all %>
        <%= link_to "Hide deactivated", employees_path(query: params[:query]), class: 'btn btn-outline-success' %>
      <% else %>
        <%= link_to "Show deactivated", employees_path(all: "true", query: params[:query]), class: 'btn btn-outline-danger' %>
      <% end %>
    </div>
  </div>
<% end %>

app/views/employees/_table.html.erb
<%= turbo_frame_tag "employes", class: "table" do %>
  <table class="table table-hover">
    <thead class="table-secondary">
      <tr>
        <th scope="col"><%= sort_link column: "code", label: "EmpNumber", table: @employees.table_name %></th>
        <th scope="col"><%= sort_link column: "last_name", label: "Name", table: @employees.table_name %></th>
        <th scope="col"><%= sort_link column: "job_id", label: "Title", table: @employees.table_name %></th>
        <th scope="col"><%= sort_link column: "employee_status_id", label: "Status", table: @employees.table_name %></th>
        <th scope="col">Delete</th>
      </tr>
    </thead>
    <tbody>
      <% @employees.each do |employee| %>
      <tr>
        <th scope="row"><%= employee.code %></th>
        <td><%= link_to employee.full_name, edit_employee_path(employee) %></td>
        <td><%= employee.job.name %></td>
        <td><%= employee.employee_status.name %></td>
        <td>
          <%= link_to 'Delete', employee_path(employee),
                  method: :delete,
                  data: { confrim: 'Are you sure?' } %> 
        </td>
      </tr>
      <% end %>
    </tbody>
  </table>
<% end %>

app/views/employees/edit.html.erb
<h1>Edit <%= @employee.full_name %></h1>

<%= render 'form', employee: @employee %>

app/views/employees/index.html.erb
<div class="row mb-3">
  <div class="col-md-6">
    <h1>Employees</h1>
  </div>
  <div class="col-md-6 text-end">
    <%= button_to 'New Employee', new_employee_path, class: "btn btn-outline-primary", method: :get %>
  </div>
</div>

<%= render 'employees/search_form' %>
<%= render 'employees/table' %>
<div class="digg_pagination">
  <%= will_paginate @employees %>
</div>
<%= "#{@employees.count} employees found." %>

app/views/employees/new.html.erb
<h1>New Employee Form</h1>

<%= render 'form', employee: @employee %>

app/views/employees/show.html.erb
<h1><%= "#{@employee.full_name}" %></h1>


<% if @employee.subordinates.count > 0 %>
<h2>Direct Reports</h2>
  <ul>
  <% @employee.subordinates.each do |sub| %>
    <li><%= link_to sub.full_name, sub %></li>
  <% end %>
  </ul>
<% end %>

app/views/jobs/_form.html.erb
<%= form_with model: job do |form| %>
  <div class="row g-2">
    <div class="col-md-4">
      <%= form.label :code, class: 'form-label' %>
      <%= form.text_field :code, class: 'form-control' %>
      <% job.errors.full_messages_for(:code).each do |message| %>
        <div class=""><%= message %></div>
      <% end %>
    </div>
    <div class="w-100"></div>
    <div class="col-md-4">
      <%= form.label :name, class: 'form-label' %>
      <%= form.text_field :name, class: 'form-control' %>
      <% job.errors.full_messages_for(:name).each do |message| %>
        <div class=""><%= message %></div>
      <% end %>
    </div>

    <div class="col-md-12">
      <%= form.submit class: 'btn btn-primary' %>
    </div>

    

    
  </div>
    

<% end %>

app/views/jobs/_table.html.erb
<div class="table">
  <table class="table table-hover">
    <thead class="table-secondary">
      <tr>
        <th scope="col"><%= sort_link(column: 'code', label: 'Code', table: 'jobs') %></th>
        <th scope="col"><%= sort_link(column: 'name', label: 'Name', table: 'jobs') %></th>
        <th scope="col">Delete</th>
      </tr>
    </thead>
    <tbody>
      <% @jobs.each do |job| %>
      <tr>
        <th scope="row"><%= job.code %></th>
        <td><%= link_to job.name, edit_job_path(job) %></td>
        <td>
          <%= link_to 'Delete', job_path(job),
                  method: :delete,
                  data: { confrim: 'Are you sure?' } %> 
        </td>
      </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/jobs/edit.html.erb
<h1>Edit <%= @job.name %></h1>

<%= render 'form', job: @job %>

app/views/jobs/index.html.erb
<div class="row mb-3">
  <div class="col-md-6">
    <h1>Jobs</h1>
  </div>
  <div class="col-md-6 text-end">
    <%= button_to 'New Job', new_job_path, class: "btn btn-outline-primary", method: :get %>
  </div>
</div>
<%= render 'jobs/table' %>

app/views/jobs/new.html.erb
<h1>New Job</h1>
<%= render 'form', job: @job %>

app/views/jobs/show.html.erb
<h1><%= "#{@job.name} - #{@job.code}" %></h1>

app/views/layouts/_flash.html.erb
<% if notice %>
  <div class="alert alert-success" role="alert">
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-danger" role="alert">
    <%= alert %>
  </div>
<% end %>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <%= link_to 'EmpMgr', root_path, class: "navbar-brand" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <% if user_signed_in? %>
          <li class="nav-item">
            <%= link_to "Empoyees", employees_path, class: "nav-link active" %>
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              Admin
            </a>
            <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
              <li><%= link_to "Jobs", jobs_path, class: "dropdown-item" %></li>
              <li><%= link_to "Orgs", orgs_path, class: "dropdown-item" %></li>
              <li><%= link_to "Statuses", employee_statuses_path, class: "dropdown-item" %></li>
              <li><%= link_to "Users", users_path, class: "dropdown-item" %></li>
            </ul>
          </li>
          <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            <%= current_user.first_name %>
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            <li><%= link_to "Profile", edit_user_registration_path, class: "dropdown-item" %></li>
            <li><%= link_to "Sign Out", destroy_user_session_path, method: :delete, class: "dropdown-item" %></li>
          </ul>
        </li>
        <% else  %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link active" %>
          </li>
        <% end %>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>EmployeeManager</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navbar' %>
    <div class="container py-3">
      <%= render 'layouts/flash' %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/orgs/_form.html.erb
<%= form_with model: org do |form| %>
  <div class="row mb-2">
    <div class="col-md-4">
      <%= form.label :code, class: 'form-label' %>
      <%= form.text_field :code, class: 'form-control' %>
      <% org.errors.full_messages_for(:code).each do |message| %>
        <div class=""><%= message %></div>
      <% end %>
    </div>
  </div>

  <div class="row mb-2">
      <div class="col-md-4">
        <%= form.label :name, class: 'form-label' %>
        <%= form.text_field :name, class: 'form-control' %>
        <% org.errors.full_messages_for(:name).each do |message| %>
          <div class=""><%= message %></div>
        <% end %>
      </div>
    </div>

    <div class="col-auto">
      <%= form.submit class: 'btn btn-primary' %>
    </div>
    
  </div>
<% end %>

app/views/orgs/_table.html.erb
<div class="table">
  <table class="table table-hover">
    <thead class="table-secondary">
      <tr>
        <th scope="col"><%= sort_link(column: 'code', label: 'Code', table: 'orgs') %></th>
        <th scope="col"><%= sort_link(column: 'name', label: 'Name', table: 'orgs') %></th>
        <th scope="col">Delete</th>
      </tr>
    </thead>
    <tbody>
      <% @orgs.each do |org| %>
      <tr>
        <th scope="row"><%= org.code %></th>
        <td><%= link_to org.name, edit_org_path(org) %></td>
        <td>
          <%= link_to 'Delete', org_path(org),
                  method: :delete,
                  data: { confrim: 'Are you sure?' } %> 
        </td>
      </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/orgs/edit.html.erb
<h1>Edit Org</h1>

<%= render 'form', org: @org %>

app/views/orgs/index.html.erb
<div class="row mb-3">
  <div class="col-md-6">
    <h1>Organizations</h1>
  </div>
  <div class="col-md-6 text-end">
    <%= button_to 'New Org', new_org_path, class: "btn btn-outline-primary", method: :get %>
  </div>
</div>

<%= render 'orgs/table' %>

app/views/orgs/new.html.erb
<h1>New Org</h1>

<%= render 'form', org: @org %>

app/views/orgs/show.html.erb
<h1><%= "#{@org.name} - #{@org.code}" %></h1>

app/views/users/_table.html.erb
<div class="table">
  <table class="table table-hover">
    <thead class="table-secondary">
      <tr>
        <th scope="col">Name</th>
        <th scope="col">Approved?</th>
        <th scope="col">Edit</th>

      </tr>
    </thead>
    <tbody>
      <% @users.each do |user| %>
      <tr>
        <th scope="row"><%= "#{user.first_name} #{user.last_name}" %></th>
        <th scope="row"><%= user.approved? %></th>
      </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/users/index.html.erb
<h1>Users</h1>
<%= render 'users/table' %>